---
- name: Ensure automation gateway container is running before initialization
  containers.podman.podman_container:
    name: automation-gateway
    state: started
  run_once: true

- name: Wait for automation gateway manage CLI availability
  ansible.builtin.command:
    cmd: podman exec automation-gateway aap-gateway-manage --help
  register: automationgateway_manage_cli
  changed_when: false
  failed_when: false
  run_once: true
  retries: 30
  delay: 5
  until: automationgateway_manage_cli.rc == 0

- name: Initialize the automation gateway database
  ansible.builtin.command:
    cmd: podman exec automation-gateway aap-gateway-manage migrate --noinput
  register: automationgateway_migrate
  changed_when: "'No migrations to apply' not in automationgateway_migrate.stdout"
  run_once: true
  retries: 5
  delay: 60
  until: automationgateway_migrate is not failed

- name: Create django super user
  ansible.builtin.command:
    cmd: >-
      podman exec automation-gateway aap-gateway-manage createsuperuser
      --username={{ gateway_admin_user }} --email={{ gateway_admin_email }}
      --noinput
  register: automationgateway_createsuperuser
  changed_when: "'Superuser created successfully' in automationgateway_createsuperuser.stdout"
  failed_when:
    - "'That username is already taken' not in automationgateway_createsuperuser.stderr"
    - "'Superuser created successfully' not in automationgateway_createsuperuser.stdout"
  run_once: true
  retries: 5
  delay: 60
  until: automationgateway_createsuperuser is not failed

- name: Update django super user password
  ansible.builtin.command:
    cmd: >-
      podman exec automation-gateway aap-gateway-manage update_password
      --username={{ gateway_admin_user }} --password={{ gateway_admin_password }}
  register: automationgateway_updatesuperuser
  changed_when: "'Password updated' in automationgateway_updatesuperuser.stdout"
  failed_when:
    - automationgateway_updatesuperuser is failed
    - not "'User matching query does not exist' in automationgateway_updatesuperuser.stderr"
  no_log: true
  run_once: true
  retries: 5
  delay: 30
  until: automationgateway_updatesuperuser is not failed

- name: Initialize authenticators
  ansible.builtin.command:
    cmd: podman exec automation-gateway aap-gateway-manage authenticators --initialize
  register: automationgateway_authenticators
  changed_when: "'Created default local authenticator' in automationgateway_authenticators.stdout"
  run_once: true
  retries: 5
  delay: 60
  until: automationgateway_authenticators is not failed
